name: My Workflow
on: 
 workflow_dispatch:


jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: My Action
      uses: benosul/SomeTests@main
      # Put an example of your mandatory inputs here
      with:
        reportType: 'User'
        dirPath: './'

    - name: Sanity Check
      run: |
       ls -a 
