name: My Workflow
on: 
 workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run action

      # Put your action repo here
      uses: benosul/SomeTests@master

      # Put an example of your mandatory inputs here
      with:
        myInput: User
      
