name: My Workflow
on: 
 workflow_dispatch:


jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run action
      # Put your action repo here
      uses: benosul/SomeTests@main
      # Put an example of your mandatory inputs here
      with:
        reportType: 'User'
        dirPath: './'
